### ISSUE TITLE
Add compatibility with instagram

### ISSUE THREAD

**Issue by ghost** [pixelcatapp/Pixelcat#5]
Add the possibility of instagram too

**Comment by pavanchow** [comment]
[Pixelfex](https://pixelfed.org/) is an free and open-source self-hosted alternative for Instagram. We can observe from the documentation that [this application](https://github.com/pixelcatapp/Pixelcat) is compatible with widely used FOSS social networking services and isn't compatible with proprietary social networking services and sites which tracks(surveillance) every movement of the user.

**Comment by polarhive** [comment]
> Add the possibility of instagram too

Try https://github.com/austinhuang0131/barinsta

**Comment by connyduck** [comment]
There will be no support for proprietary networks.
